CREATE TABLE mytable(
   Name        VARCHAR(7) NOT NULL PRIMARY KEY
  ,Creator     VARCHAR(66)
  ,Year        INTEGER 
  ,Description VARCHAR(686)
  ,FIELD5      VARCHAR(30)
);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('C','Dennis Ritchie',1972,'C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system. By design, C provides constructs that map efficiently to typical machine instructions. It has found lasting use in applications previously coded in assembly language. Such applications include operating systems and various application software for computers architectures that range from supercomputers to PLCs and embedded systems.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('C++','Bjarne Stroustrup',2017,'C++ is a general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language, or "C with Classes". The language has expanded significantly over time, and modern C++ now has object-oriented, generic, and functional features in addition to facilities for low-level memory manipulation. It is almost always implemented as a compiled language, and many vendors provide C++ compilers, including the Free Software Foundation, LLVM, Microsoft, Intel, Oracle, and IBM, so it is available on many platforms.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Clojure','Rick Hickey',2007,'Clojure is a modern, dynamic, and functional dialect of the Lisp programming language on the Java platform.[17][18] Like other Lisps, Clojure treats code as data and has a Lisp macro system. The current development process is community-driven, overseen by Rich Hickey as its benevolent dictator for life (BDFL).',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Cobra','Charles Esterbrook',2013,'Cobra is a discontinued general-purpose, object-oriented programming language. Cobra is designed by Charles Esterbrook, and runs on the Microsoft .NET and Mono platforms. It is strongly influenced by Python, C#, Eiffel, Objective-C, and other programming languages. It supports both static and dynamic typing. It has support for unit tests and contracts. It has lambda expressions, closures, list comprehensions, and generators.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Comtran','Bob Bemer',1957,'COMTRAN (COMmercial TRANslator) is an early programming language developed at IBM. It was intended as the business programming equivalent of the scientific programming language FORTRAN (FORmula TRANslator). It served as one of the forerunners to the COBOL language. Developed by Bob Bemer, in 1957, the language was the first to feature the programming language element known as a picture clause.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('CSS','Håkon Wium Lie, Bert Bos',1996,'Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language like HTML. CSS is a cornerstone technology of the World Wide Web, alongside HTML and JavaScript.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Emerald','Andrew P. Black, Norman C. Hutchinson, Eric B. Jul, Henry M. Levys',1980,'Emerald was designed to support high performance distribution, location, and high performance of objects, to simplify distributed programming, to exploit information hiding, and to be a small language.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Fantom','Brian Frank, Andy Frank',2005,'Fantom is a general purpose object-oriented programming language created by Brian and Andy Frank that runs on the Java Runtime Environment (JRE), JavaScript, and the .NET Common Language Runtime (CLR) (.NET support is considered "prototype"[5] status). Its primary design goal is to provide a standard library API that abstracts away the question of whether the code will ultimately run on the JRE or CLR. Like C# and Java, Fantom uses a curly brace syntax. The language supports functional programming through closures and concurrency through the Actor model. Fantom takes a "middle of the road" approach to its type system, blending together aspects of both static and dynamic typing.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Fortran','John Backus',1957,'Fortran is a general-purpose, compiled imperative programming language that is especially suited to numeric computation and scientific computing.',NULL);
INSERT INTO mytable(Name,Creator,Year,Description,FIELD5) VALUES ('Java','James Gosling',1995,'Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA), meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.',NULL);
